### ISSUE TITLE
Soporte para tildes

### ISSUE THREAD

**Issue by adrigrillo** [ggrandes/log4j2-simplejson#2]
Buenas,

Me gustaría saber en que momento del proceso se codifica el string que constituye el JSON final, ya que los caracteres con tildes son transformados a su codificación alfanumérica, del tipo ("\u00E1"), representando de forma incorrecta los mensajes con tildes.

He probado a cambiar la codificación del charset que viene en el método _createLayout()_ pero nada.

Gracias y un saludo.

**Comment by ggrandes** [comment]
No quisiera responder con Aviones si preguntas por Trenes, pero... realmente quieres hacer eso? me explico, json permite q los caracteres "raros" se escapen siguiendo la codificacion Unicode, en realidad todos los caracteres, incluso los US-ASCII se podrían escapar:

![json-string](https://user-images.githubusercontent.com/2364301/29028684-643f6882-7b85-11e7-8c79-c021822f5093.gif)

Si tienes un parser de json standard solo tienes que leer el valor y devolverá ese "\u00E1" a su valor humano. Yo opté por escapar todos los no US-ASCII (modo conservador) al encontrarme con muchos problemas de codificacion mezclada de ISO-8859-1, 8859-15, Windows-1252, UTF-8, etc. Digamos q el parametro charset del createLayout en la practica es como si estuviera hardcoded, la documentacion vale como referencia para saber q va a salir por el json.

No obstante, si estas convencido que quieres cambiar el codigo... (no lo recomiendo), el escapado de los Strings se hace en: [EncoderJSON.java](https://github.com/ggrandes/log4j2-simplejson/blob/master/src/main/java/org/javastack/log4j/simplejson/EncoderJSON.java)

**Comment by adrigrillo** [comment]
A veces, es bueno responder con aviones. Lo primero, muchas gracias por la explicación. Me parece que seguiré tu consejo y mantendré la cosa como está, a no ser que me pidan lo contrario.

Por otro lado, gracias por abrir esta librería, es justo lo que necesitaba para el proyecto en el que estoy trabajando y, sin ella, todavía me estaría pegando con el JSON layout por defecto. (Acabo de terminar la carrera y todavía no me vería capaz de hacer una cosa así en los tiempos de entrega que tenemos).

Siento si este no era el sitio para esta pregunta, pero no encontré otra forma de ponerme en contacto contigo, gracias de nuevo por responder.

**Comment by ggrandes** [comment]
Todo perfecto. Me alegra que el codigo sea util!
